import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "./components/Header";
import { TodoThemeProvider } from "./context/TodoThemeContext";


const poppins=Poppins({
  weight: ['400','500','600','700'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TodoThemeProvider>
        <body className={poppins.className} >
          <Header />
          {children}
        </body>
      </TodoThemeProvider>
    </html>
  );
}
